### ISSUE TITLE
Linking fails on Linux - no -lpthreads

### ISSUE THREAD

**Issue by eyalroz** [darealshinji/mkvextract-gui#1]
When I use the fltk-config on Devuan GNU/Linux Chimaera to build mkvextract-gui, the gcc command is missing -lpthread, causing linking to fail.

**Comment by darealshinji** [comment]
Sounds like a bug in fltk-config. You can open the fltk-config script in an editor and remove instances of `-lpthread` or try to replace them with `-pthread`.

**Comment by eyalroz** [comment]
@darealshinji : Not sure it's a bug... `libpthread.so` does exist...

**Comment by darealshinji** [comment]
Ah, you need to **add** pthread to the linker flags, I see. Try to edit fltk-config or copy and paste the output like with the build flags from console, edit that one and run the compile command manually. I could also compile the app and push a release if that helps.

**Comment by eyalroz** [comment]
I did add the link flag manually, and it did work, but - I'm suggesting that you do something so that the FLTK-based build of this repository would "just work". I'm not sure if it's your repo's responsibility or maybe it's an FLTK issue - but I certainly cannot coordinate with the FLTK maintainer(s) since this is not my repo and I'm not familiar with FLTK.

**Comment by darealshinji** [comment]
I have added a build script that should hopefully make compiling easy on most systems. I've also pushed a release and uploaded a pre-build binary.

**Comment by eyalroz** [comment]
I'll try it out soon. Thanks.

**Comment by darealshinji** [comment]
I have just fixed a bug and pushed a new release.
